config/routes.php
<?php
/**
 * Routes configuration
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * CakePHP(tm) : Rapid Development Framework (https://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 * @link          https://cakephp.org CakePHP(tm) Project
 * @license       https://opensource.org/licenses/mit-license.php MIT License
 */

use Cake\Core\Plugin;
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;
use Cake\Routing\Route\DashedRoute;

/**
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass()`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 *
 * Cache: Routes are cached to improve performance, check the RoutingMiddleware
 * constructor in your `src/Application.php` file to change this behavior.
 *
 */
Router::defaultRouteClass(DashedRoute::class);

Router::scope('/', function (RouteBuilder $routes) {
    /**
     * Apply a middleware to the current route scope.
     * Requires middleware to be registered via `Application::routes()` with `registerMiddleware()`
     */
    $routes->applyMiddleware('csrf');

    /**
     * Here, we are connecting '/' (base path) to a controller called 'Pages',
     * its action called 'display', and we pass a param to select the view file
     * to use (in this case, src/Template/Pages/home.ctp)...
     */
   // $routes->connect('/', ['controller' => 'Pages', 'action' => 'display', 'home']); //comentamos el home por defecto de cake

    $routes->connect('/', ['controller' => 'proyectos', 'action' => 'listar']);

    /**
     * ...and connect the rest of 'Pages' controller's URLs.
     */
    $routes->connect('/pages/*', ['controller' => 'Pages', 'action' => 'display']);

    /**
     * Connect catchall routes for all controllers.
     *
     * Using the argument `DashedRoute`, the `fallbacks` method is a shortcut for
     *
     * ```
     * $routes->connect('/:controller', ['action' => 'index'], ['routeClass' => 'DashedRoute']);
     * $routes->connect('/:controller/:action/*', [], ['routeClass' => 'DashedRoute']);
     * ```
     *
     * Any route class can be used with this method, such as:
     * - DashedRoute
     * - InflectedRoute
     * - Route
     * - Or your own route class
     *
     * You can remove these routes once you've connected the
     * routes you want in your application.
     */
    $routes->fallbacks(DashedRoute::class);
});

/**
 * If you need a different set of middleware or none at all,
 * open new scope and define routes there.
 *
 * ```
 * Router::scope('/api', function (RouteBuilder $routes) {
 *     // No $routes->applyMiddleware() here.
 *     // Connect API actions here.
 * });
 * ```
 */

src/Model/Entity/Contenido.php
<?php
namespace App\Model\Entity;

use Cake\ORM\Entity;

/**
 * Contenido Entity
 *
 * @property int $id
 * @property int $id_tecnico
 * @property int $id_informe
 * @property int $id_fase
 * @property string $concepto
 * @property string $descripcion
 * @property \Cake\I18n\FrozenDate $fecha_ini
 * @property \Cake\I18n\FrozenDate $fecha_fin
 * @property \Cake\I18n\FrozenTime $fecha_add
 * @property \Cake\I18n\FrozenTime $fecha_mod
 */
class Contenido extends Entity
{

    /**
     * Fields that can be mass assigned using newEntity() or patchEntity().
     *
     * Note that when '*' is set to true, this allows all unspecified fields to
     * be mass assigned. For security purposes, it is advised to set '*' to false
     * (or remove it), and explicitly make individual fields accessible as needed.
     *
     * @var array
     */
    protected $_accessible = [
        'id_tecnico' => true,
        'id_informe' => true,
        'id_fase' => true,
        'concepto' => true,
        'descripcion' => true,
        'fecha_ini' => true,
        'fecha_fin' => true,
        'fecha_add' => true,
        'fecha_mod' => true
    ];

    // prueva de virtual propieters
/*    protected function _getCampoCalculado()
    {
        return $this->_properties['fecha_ini'] . '  ' .
               $this->_properties['fecha_fin'];
    }  */
}

src/Model/Table/ContenidosTable.php
<?php
namespace App\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

use Cake\I18n\Date;
use Cake\ORM\TableRegistry;

/**
 * Contenidos Model
 *
 * @method \App\Model\Entity\Contenido get($primaryKey, $options = [])
 * @method \App\Model\Entity\Contenido newEntity($data = null, array $options = [])
 * @method \App\Model\Entity\Contenido[] newEntities(array $data, array $options = [])
 * @method \App\Model\Entity\Contenido|bool save(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\Contenido|bool saveOrFail(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\Contenido patchEntity(\Cake\Datasource\EntityInterface $entity, array $data, array $options = [])
 * @method \App\Model\Entity\Contenido[] patchEntities($entities, array $data, array $options = [])
 * @method \App\Model\Entity\Contenido findOrCreate($search, callable $callback = null, $options = [])
 */
class ContenidosTable extends Table
{

    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->setTable('contenidos');
        $this->setDisplayField('id');
        $this->setPrimaryKey('id');

        $this->belongsTo('Tecnicos')
            ->setForeignKey('id_tecnico')
            ->setDependent(false);  

        $this->belongsTo('Fases')
            ->setForeignKey('id_fase')
            ->setDependent(false);    

        $this->belongsTo('Informes')
         //   ->setBindingKey('Informe.id')
            ->setForeignKey('id_informe')
     //       ->setJoinType('INNER')
            ->setDependent(false);  
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator)
    {
        $validator
            ->integer('id')
            ->allowEmpty('id', 'create');

        $validator
            ->integer('id_tecnico')
            ->requirePresence('id_tecnico', 'create')
            ->notEmpty('id_tecnico');

        $validator
            ->integer('id_informe')
            ->requirePresence('id_informe', 'create')
            ->notEmpty('id_informe');

        $validator
            ->integer('id_fase')
            ->requirePresence('id_fase', 'create')
            ->notEmpty('id_fase');

        $validator
            ->scalar('concepto')
            ->maxLength('concepto', 30)
            ->notEmpty('concepto');

        $validator
            ->scalar('descripcion')
            ->maxLength('descripcion', 200)
            ->notEmpty('descripcion');

        $validator
            ->date('fecha_ini')
            ->notEmpty('fecha_ini');

        $validator
            ->date('fecha_fin')
            ->notEmpty('fecha_fin');

        $validator
            ->dateTime('fecha_add')
            ->allowEmpty('fecha_add');

        $validator
            ->dateTime('fecha_mod')
            ->allowEmpty('fecha_mod');

        return $validator;
    }

    public function beforeSave($event, $entity, $options) {

            if ($entity->isNew()) {

                $entity -> fecha_add = date("Y-m-d H:i:s"); 
            }else {
                $entity -> fecha_mod = date("Y-m-d H:i:s");
            }
            return true;
        
    }

    public function dameContenidosConTodo(){

        $query = $this->find('all')->contain(['Tecnicos','Fases','Informes.Proyectos']);

        return $query;
    }
/*
    public function dameContenidoInicialFinal(){

        $query = $this->find('all')
            ->where(['Contenidos.id_informe' => 72])
            ->contain(['Informes']);

        return $query;
    }  */

/*    public function dameFechaInicial(){

        $fecha_ini = new Date();
        $fecha_ini->format('Y-m-d');
        $fecha_ini->setDate(2018, 01, 01);

        $query = $this->find('all')
            ->where([])   


    } */

    public function dameContenidosInformeEstidio(){

        $query = $this->find('all')
            ->where(['Contenidos.id_informe' => 72])
            ->contain(['Informes']);    

        return $query;
    }

    public function dameInformeParaCrearContenido($idInforme){

        $query = TableRegistry::get('Informes')->find('all')
            ->where(['Informes.id' => $idInforme])
            ->contain(['Proyectos']);

        return $query->toArray();    
    }





}

src/Controller/ContenidosController.php
<?php
namespace App\Controller;

use App\Controller\AppController;
// use Cake\ORM\TableRegistry;

/**
 * Contenidos Controller
 *
 * @property \App\Model\Table\ContenidosTable $Contenidos
 *
 * @method \App\Model\Entity\Contenido[]|\Cake\Datasource\ResultSetInterface paginate($object = null, array $settings = [])
 */
class ContenidosController extends AppController
{

    /**
     * Index method
     *
     * @return \Cake\Http\Response|void
     */
    public function listar()
    {
        $this->paginate = [
        'sortWhitelist' => [
            'id','id_tecnico','Tecnicos.nombre','id_informe', 'Proyectos.nombre_app','id_fase', 'Fases.concepto'
            ]
        ];
     //   $contenidos = $this->paginate($this->Contenidos);
        $contenidos = $this->Contenidos->dameContenidosConTodo();
        $this->set('contenidos', $this->paginate($contenidos));
        $contenidos -> toArray();

        $this->set(compact('contenidos'));
    }

    /**
     * View method
     *
     * @param string|null $id Contenido id.
     * @return \Cake\Http\Response|void
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function ver($id = null)
    {

        $miscontenidos = $this->Contenidos->dameContenidosInformeEstidio();
        $miscontenidos -> toArray();

        $contenido = $this->Contenidos->get($id, [
            'contain' => []
        ]);

   //    debug($contenidos); 

      //  $this->set('contenido', $contenido);
        $this->set(compact('contenido','miscontenidos'));
    }

    /**
     * Add method
     *
     * @return \Cake\Http\Response|null Redirects on successful add, renders view otherwise.
     */
 /*   public function crear($idGrupo = null)
    {
        $dataA = $this->loadModel('Tecnicos')->dameTecnicosPosibles($idGrupo);
        $dataB = $this->loadModel('Informes')->dameInformesConTipo();
        $dataC = $this->loadModel('Fases')->dameFases();

        $contenido = $this->Contenidos->newEntity();
        if ($this->request->is('post')) {
            
            $contenido = $this->Contenidos->patchEntity($contenido, $this->request->getData());

            if ($this->Contenidos->save($contenido)) {
                $this->Flash->success(__('Los datos del nuevo contenido han sido guardados.'));

                return $this->redirect(['action' => 'listar']);
            }
            $this->Flash->error(__('Algo ha fallado. Inténtelo de nuevo.'));
        }
        $this->set(compact('contenido', 'dataA', 'dataB', 'dataC'));
    }  */


       public function crear($idGrupo = null)
    {
        $idInforme = $this->request->getData('idInforme');
   //     debug($idInforme);

        $carga = $this->loadModel('Informes');

        $informeSeleccionado = $carga->dameGrupoDeInforme($idInforme);
        $informeSeleccionado->toArray();

        foreach ($informeSeleccionado as $i) {
            if(isset($i->proyecto->id_grupo)){

                $idGrupo = $i->proyecto->id_grupo;
            }
        }

        $dataA = $this->loadModel('Tecnicos')->dameTecnicosPosibles($idGrupo);
        $dataB = $carga->dameInformesConTipo();
        $dataC = $this->loadModel('Fases')->dameFases();

        $contenido = $this->Contenidos->newEntity();

        $contenido = $this->Contenidos->patchEntity($contenido, $this->request->getData());

            if ($this->Contenidos->save($contenido)) {
                $this->Flash->success(__('Los datos del nuevo contenido han sido guardados.'));

                return $this->redirect(['action' => 'listar']);
            }
            if ($idGrupo == null) {
                $this->Flash->error(__('Algo ha fallado. Inténtelo de nuevo.'));                
            }
            $this->set(compact('contenido', 'dataA', 'dataB', 'dataC','idInfo'));
    }



    public function seleccionarinformeparacrear(){

        $informes = $this->loadModel('Informes')->dameInformesConTipo();
        $this->set(compact('informes'));

    }
/*
    public function creardesdecontenido()
    {

        $dato = $this->request->getData();

        $carga = $this->loadModel('Contenidos');
        $valor = $dato['idInforme'];

        $dato2 = $carga->dameInformeParaCrearContenido($valor);

        $dataA = $this->loadModel('Tecnicos')->dameTecnicosPosibles($dato2[0]->proyecto->id_grupo);
        $dataB = $this->loadModel('Informes')->dameInformesConTipo();
        $dataC = $this->loadModel('Fases')->dameFases();

        

            $contenido = $this->Contenidos->newEntity();
            if ($this->request->is('post')) {
                
                $contenido = $this->Contenidos->patchEntity($contenido, $this->request->getData());



                if ($this->Contenidos->save($contenido)) {
                    $this->Flash->success(__('Los datos del nuevo contenido han sido guardados.'));

                    return $this->redirect(['action' => 'listar']);
                }
                if($valor != null){

                }else{
                    $this->Flash->error(__('Algo ha fallado. Inténtelo de nuevo.'));
                }
                $this->Flash->error(__('Algo ha fallado. Inténtelo de nuevo.'));
            }
            $this->set(compact('contenido', 'dataA', 'dataB', 'dataC'));

        
    }    */


    /**
     * Edit method
     *
     * @param string|null $id Contenido id.
     * @return \Cake\Http\Response|null Redirects on successful edit, renders view otherwise.
     * @throws \Cake\Network\Exception\NotFoundException When record not found.
     */
    public function editar($id = null)
    {
        $dataA = $this->loadModel('Tecnicos')->dameTecnicos();
        $dataB = $this->loadModel('Informes')->dameInformes();
        $dataC = $this->loadModel('Fases')->dameFases();

        $contenido = $this->Contenidos->get($id, [
            'contain' => []
        ]);
        if ($this->request->is(['patch', 'post', 'put'])) {
            $contenido = $this->Contenidos->patchEntity($contenido, $this->request->getData());
            if ($this->Contenidos->save($contenido)) {
                $this->Flash->success(__('Los datos del contenido han sido actualizados.'));

                return $this->redirect(['action' => 'listar']);
            }
            $this->Flash->error(__('Algo ha fallado. Inténtelo de nuevo.'));
        }
        $this->set(compact('contenido', 'dataA', 'dataB', 'dataC'));
    }

    /**
     * Delete method
     *
     * @param string|null $id Contenido id.
     * @return \Cake\Http\Response|null Redirects to index.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function eliminar($id = null)
    {
        $this->request->allowMethod(['post', 'eliminar']);
        $contenido = $this->Contenidos->get($id);
        if ($this->Contenidos->delete($contenido)) {
            $this->Flash->success(__('El contenido ha sido eliminado del registro.'));
        } else {
            $this->Flash->error(__('Algo ha fallado. Inténtelo de nuevo.'));
        }

        return $this->redirect(['action' => 'listar']);
    }

}

src/Template/Contenidos/crear.ctp
<?php
/**
 * @var \App\View\AppView $this
 * @var \App\Model\Entity\Contenido $contenido
 */
?>
<div class="content-box-large">
    <p>
        <button class="btn btn-primary"><?= $this->Html->link(__('Ver todos'), ['action' => 'listar']) ?> </button>
    </p>  
    <div class="panel-heading">
        <div class="panel-title">Nuevo Contenido</div>
        <div class="panel-body">
            <fieldset>
                <div class="form-group">
                    <?php 
                        echo $this->Form->create($contenido);
                        echo '<div class="form-group col-md-10">';
                        echo $this->Form->control('id_tecnico', ['type' => 'select','label' => 'Técnico', 'options' => $dataA, 'class' => 'form-control']);
                        echo '</div>';
                        echo '<div class="form-group col-md-10">';
                        echo $this->Form->control('id_informe', ['type' => 'select','label' => 'Informe', 'options' => $dataB, 'class' => 'form-control']);
                        echo '</div>'; 
                        echo '<div class="form-group col-md-10">';
                        echo $this->Form->control('id_fase', ['type' => 'select','label' => 'Fase', 'options' => $dataC, 'class' => 'form-control']);
                        echo '</div>';
                        echo '<div class="form-group col-md-10">';
                        echo $this->Form->control('concepto', ['type' => 'text', 'label' => 'Concepto', 'class' => 'form-control']);
                        echo '</div>';
                        echo '<div class="form-group col-md-10">';
                        echo $this->Form->control('descripcion', ['type' => 'textarea', 'label' => 'Descripción', 'class' => 'form-control', 'rows' => '5', 'cols' => '5']);
                        echo '</div>';
                        echo '<div class="form-group col-md-10">';
                        echo '<label for="calendario">Inicio</label>';
                        echo '<input class="form-control" type="date" id="calendario" name="fecha_ini">';
                        echo '</div>';
                        echo '<div class="form-group col-md-10">';
                        echo '<label for="calendario">Fin</label>';
                        echo '<input class="form-control" type="date" id="calendario" name="fecha_fin">';
                        echo '</div>';
                        echo '<div class="form-group col-md-10">';
                        echo $this->Form->submit('Enviar',['class' => 'btn btn-primary form-group']);
                        echo '</div>'; 
                        echo $this->Form->end(); 
                    ?>
                </div>                        
            </fieldset>
        </div>
    </div>
</div>
     <!--        <label for="calendario">Inicio</label>
            <input type="date" id="calendario" name="fecha_ini">   
            <div class="panel-body">
                <h5>Inicio</h5>
                <p>
                    <div class="bfh-datepicker" id="calendario" name="fecha_ini" data-format="y-m-d" data-date="today"></div>
                </p>
                <h5>Fin</h5>
                <p>
                    <div class="bfh-datepicker" id="calendario" name="fecha_fin" data-format="y-m-d" data-date="today"></div>
                </p>
            </div>   -->
            

src/Template/Contenidos/editar.ctp
<?php
/**
 * @var \App\View\AppView $this
 * @var \App\Model\Entity\Contenido $contenido
 */
?>
<div class="content-box-large">
    <p>
        <button class="btn btn-primary">
            <?= $this->Html->link(__('Ver'), ['action' => 'ver', $contenido->id]) ?>
        </button>
        <button class="btn btn-primary"><?= $this->Form->postLink(__('Eliminar'), ['action' => 'eliminar', $contenido->id], ['confirm' => __('Está seguro de eliminar el contenido con identificador # {0}?', $contenido->id)]) ?></button>
        <button class="btn btn-primary"><?= $this->Html->link(__('Todos'), ['action' => 'listar']) ?> </button>
        <button class="btn btn-primary"><?= $this->Html->link(__('Crear'), ['action' => 'seleccionarinformeparacrear']) ?></button>
    </p>  
    <div class="panel-heading">
        <div class="panel-title">Nuevo Contenido</div>
        <div class="panel-body">
            <fieldset>
                <div class="form-group">
                    <?php 
                        echo $this->Form->create($contenido);
                        echo '<div class="form-group col-md-10">';
                        echo $this->Form->control('id_tecnico', ['type' => 'select','label' => 'Técnico', 'options' => $dataA, 'class' => 'form-control']);
                        echo '</div>';
                        echo '<div class="form-group col-md-10">';
                        echo $this->Form->control('id_informe', ['type' => 'select','label' => 'Informe', 'options' => $dataB, 'class' => 'form-control']);
                        echo '</div>'; 
                        echo '<div class="form-group col-md-10">';
                        echo $this->Form->control('id_fase', ['type' => 'select','label' => 'Fase', 'options' => $dataC, 'class' => 'form-control']);
                        echo '</div>';
                        echo '<div class="form-group col-md-10">';
                        echo $this->Form->control('concepto', ['type' => 'text', 'label' => 'Concepto', 'class' => 'form-control']);
                        echo '</div>';
                        echo '<div class="form-group col-md-10">';
                        echo $this->Form->control('descripcion', ['type' => 'textarea', 'label' => 'Descripción', 'class' => 'form-control', 'rows' => '5', 'cols' => '5']);
                        echo '</div>';
                        echo '<div class="form-group col-md-10">';
                        echo '<label for="calendario">Inicio</label>';
                        echo '<input class="form-control" type="date" id="calendario" name="fecha_ini">';
                        echo '</div>';
                        echo '<div class="form-group col-md-10">';
                        echo '<label for="calendario">Fin</label>';
                        echo '<input class="form-control" type="date" id="calendario" name="fecha_fin">';
                        echo '</div>';
                        echo '<div class="form-group col-md-10">';
                        echo $this->Form->submit('Enviar',['class' => 'btn btn-primary form-group']);
                        echo '</div>'; 
                        echo $this->Form->end(); 
                    ?>
                </div>                        
            </fieldset>
        </div>
    </div>
</div>

src/Template/Contenidos/listar.ctp
<?php
/**
 * @var \App\View\AppView $this
 * @var \App\Model\Entity\Contenido[]|\Cake\Collection\CollectionInterface $contenidos
 */
?>
<div class="container-fluid">
    <div class="panel-heading">
        <div class="panel-title">Contenidos registrados</div>
        <button class="btn btn-primary"><?= $this->Html->link(__('Crear'), ['action' => 'seleccionarinformeparacrear']) ?> </button>
    </div>
    <div class="panel-body table-responsive">
        <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="example">
            <thead>
                <tr>
                    <th scope="col"><?= $this->Paginator->sort('id', ['label' => 'ID']) ?></th>
                    <th scope="col"><?= $this->Paginator->sort('id_tecnico', ['label' => 'ID Técnico']) ?></th>
                    <th scope="col"><?= $this->Paginator->sort('Tecnicos.nombre', ['label' => 'Técnico']) ?></th>
                    <th scope="col"><?= $this->Paginator->sort('Proyectos.nombre_app', ['label' => 'Proyecto']) ?></th>
                    <th scope="col"><?= $this->Paginator->sort('Fases.concepto', ['label' => 'ID Fase']) ?></th>
                    <th scope="col"><?= $this->Paginator->sort('concepto', ['label' => 'Concepto']) ?></th>
                    <th scope="col" class="actions"><?= __('Acciones') ?></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($contenidos as $contenido): ?>
                    <tr>
                        <td><?= $this->Number->format($contenido->id) ?></td>
                        <td><?= $this->Number->format($contenido->id_tecnico) ?></td>
                        <td><?= h($contenido->tecnico->nombre . ' ' . $contenido->tecnico->apellidos ) ?></td>
                        <td><?= h($contenido->informe->proyecto->nombre_app) ?></td>
                        <td><?= h($contenido->fase->concepto) ?></td>
                        <td><?= h($contenido->concepto) ?></td>
                        <td class="actions">
                            <button class="btn btn-primary btn-xs">
                                <?= $this->Html->link(__('Ver'), ['action' => 'ver', $contenido->id]) ?>
                            </button>
                            <button class="btn btn-primary btn-xs">
                                <?= $this->Html->link(__('Editar'), ['action' => 'editar', $contenido->id]) ?>
                            </button>
                            <button class="btn btn-primary btn-xs">
                                <?= $this->Form->postLink(__('Eliminar'), ['action' => 'eliminar', $contenido->id], ['confirm' => __('Está seguro de eliminar el contenido con identificador # {0}?', $contenido->id)]) ?>
                            </button> 
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
         <!--       <div class="paginator">
                    <ul class="pagination">
                        <?= $this->Paginator->first('<< ' . __('first')) ?>
                        <?= $this->Paginator->prev('< ' . __('previous')) ?>
                        <?= $this->Paginator->numbers() ?>
                        <?= $this->Paginator->next(__('next') . ' >') ?>
                        <?= $this->Paginator->last(__('last') . ' >>') ?>
                    </ul>
                    <p><?= $this->Paginator->counter(['format' => __('Page {{page}} of {{pages}}, showing {{current}} record(s) out of {{count}} total')]) ?></p>
                </div>    -->

    </div>
</div>

src/Template/Contenidos/seleccionarinformeparacrear.ctp
            <?php
/**
 * @var \App\View\AppView $this
 * @var \App\Model\Entity\Contenido $contenido
 */
?>
<!--
<nav class="large-3 medium-4 columns" id="actions-sidebar">
    <ul class="side-nav">
        <li class="heading"><?= __('Acciones') ?></li>
        <li><?= $this->Html->link(__('Ver todos'), ['action' => 'listar']) ?></li>
    </ul>
</nav>     -->
<div class="content-box-large">
    <p>
        <button class="btn btn-primary"><?= $this->Html->link(__('Ver todos'), ['action' => 'listar']) ?> </button>
    </p>  
    <div class="panel-heading">
        <div class="panel-title">Nuevo Proyecto</div>
        <div class="panel-body">
            <fieldset>
                <div class="form-group">
                    <?php
                        echo $this->Form->create('conditions', ['url' => ['action' => 'crear']]);
                        echo '<div class="form-group col-md-10">';
                        echo $this->Form->control('idInforme', ['type' => 'select','label' => 'Informes registrados', 'options' => $informes, 'class' => 'form-control']);
                        echo '</div>'; 
                        echo '<div class="form-group col-md-10">'; 
                        echo $this->Form->submit('Enviar',['class' => 'btn btn-primary form-group']);
                        echo '</div>'; 
                        echo $this->Form->end();             
                    ?>
                </div>
            </fieldset>
        </div>
    </div>
</div>