config/routes.php
<?php
/**
 * Routes configuration
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * CakePHP(tm) : Rapid Development Framework (https://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 * @link          https://cakephp.org CakePHP(tm) Project
 * @license       https://opensource.org/licenses/mit-license.php MIT License
 */

use Cake\Core\Plugin;
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;
use Cake\Routing\Route\DashedRoute;

/**
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass()`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 *
 * Cache: Routes are cached to improve performance, check the RoutingMiddleware
 * constructor in your `src/Application.php` file to change this behavior.
 *
 */
Router::defaultRouteClass(DashedRoute::class);

Router::scope('/', function (RouteBuilder $routes) {
    /**
     * Apply a middleware to the current route scope.
     * Requires middleware to be registered via `Application::routes()` with `registerMiddleware()`
     */
    $routes->applyMiddleware('csrf');

    /**
     * Here, we are connecting '/' (base path) to a controller called 'Pages',
     * its action called 'display', and we pass a param to select the view file
     * to use (in this case, src/Template/Pages/home.ctp)...
     */
   // $routes->connect('/', ['controller' => 'Pages', 'action' => 'display', 'home']); //comentamos el home por defecto de cake

    $routes->connect('/', ['controller' => 'proyectos', 'action' => 'listar']);

    /**
     * ...and connect the rest of 'Pages' controller's URLs.
     */
    $routes->connect('/pages/*', ['controller' => 'Pages', 'action' => 'display']);

    /**
     * Connect catchall routes for all controllers.
     *
     * Using the argument `DashedRoute`, the `fallbacks` method is a shortcut for
     *
     * ```
     * $routes->connect('/:controller', ['action' => 'index'], ['routeClass' => 'DashedRoute']);
     * $routes->connect('/:controller/:action/*', [], ['routeClass' => 'DashedRoute']);
     * ```
     *
     * Any route class can be used with this method, such as:
     * - DashedRoute
     * - InflectedRoute
     * - Route
     * - Or your own route class
     *
     * You can remove these routes once you've connected the
     * routes you want in your application.
     */
    $routes->fallbacks(DashedRoute::class);
});

/**
 * If you need a different set of middleware or none at all,
 * open new scope and define routes there.
 *
 * ```
 * Router::scope('/api', function (RouteBuilder $routes) {
 *     // No $routes->applyMiddleware() here.
 *     // Connect API actions here.
 * });
 * ```
 */

src/Model/Entity/Proyecto.php
<?php
namespace App\Model\Entity;

use Cake\ORM\Entity;

/**
 * Proyecto Entity
 *
 * @property int $id
 * @property int $id_grupo
 * @property int $id_estado
 * @property int $id_cliente
 * @property string $nombre_app
 * @property string $descripcion
 * @property \Cake\I18n\FrozenTime $fecha_add
 * @property \Cake\I18n\FrozenTime $fecha_mod
 */
class Proyecto extends Entity
{

    /**
     * Fields that can be mass assigned using newEntity() or patchEntity().
     *
     * Note that when '*' is set to true, this allows all unspecified fields to
     * be mass assigned. For security purposes, it is advised to set '*' to false
     * (or remove it), and explicitly make individual fields accessible as needed.
     *
     * @var array
     */
    protected $_accessible = [
        'id_grupo' => true,
        'id_estado' => true,
        'id_cliente' => true,
        'nombre_app' => true,
        'descripcion' => true,
        'fecha_add' => true,
        'fecha_mod' => true
    ];
}

src/Model/Table/ProyectosTable.php
<?php
namespace App\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

/**
 * Proyectos Model
 *
 * @method \App\Model\Entity\Proyecto get($primaryKey, $options = [])
 * @method \App\Model\Entity\Proyecto newEntity($data = null, array $options = [])
 * @method \App\Model\Entity\Proyecto[] newEntities(array $data, array $options = [])
 * @method \App\Model\Entity\Proyecto|bool save(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\Proyecto|bool saveOrFail(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\Proyecto patchEntity(\Cake\Datasource\EntityInterface $entity, array $data, array $options = [])
 * @method \App\Model\Entity\Proyecto[] patchEntities($entities, array $data, array $options = [])
 * @method \App\Model\Entity\Proyecto findOrCreate($search, callable $callback = null, $options = [])
 */
class ProyectosTable extends Table
{

    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->setTable('proyectos');
        $this->setDisplayField('id');
        $this->setPrimaryKey('id');

        $this->belongsTo('Grupos',[
            'className' => 'Proyectos.Grupos'
        ])
            ->setForeignKey('id_grupo')
            ->setJoinType('INNER')
            ->setDependent(false);

        $this->belongsTo('Estados')
            ->setForeignKey('id_estado')
            ->setJoinType('INNER')
            ->setDependent(false);

        $this->belongsTo('Clientes')
            ->setForeignKey('id_cliente')
            ->setJoinType('INNER')
            ->setDependent(false);


        $this->hasOne('Plazos')
       ->setForeignKey('id_proyecto')
        ->setDependent(false);

        $this->hasMany('Informes')
            ->setForeignKey('id_proyecto')
            ->setDependent(false);  

         

    }  

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instSance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator)
    {
        $validator
            ->integer('id')
            ->allowEmpty('id', 'create');

        $validator
            ->integer('id_grupo')
            ->requirePresence('id_grupo', 'create')
            ->notEmpty('id_grupo');

        $validator
            ->integer('id_estado')
            ->requirePresence('id_estado', 'create')
            ->notEmpty('id_estado');

        $validator
            ->integer('id_cliente')
            ->requirePresence('id_cliente', 'create')
            ->notEmpty('id_cliente');

        $validator
            ->scalar('nombre_app')
            ->maxLength('nombre_app', 60)
            ->notEmpty('nombre_app');

        $validator
            ->scalar('descripcion')
            ->maxLength('descripcion', 150)
            ->notEmpty('descripcion');

        $validator
            ->dateTime('fecha_add')
            ->allowEmpty('fecha_add');

        $validator
            ->dateTime('fecha_mod')
            ->allowEmpty('fecha_mod');

        return $validator;
    }

    public function beforeSave($event, $entity, $options) {

            if ($entity->isNew()) {

                $entity -> fecha_add = date("Y-m-d H:i:s"); 
            }else {
                $entity -> fecha_mod = date("Y-m-d H:i:s");
            }
            return true;
        
    }

    public function dameProyectosConTodo(){

        $query = $this->find('all')->contain(['Grupos','Estados','Clientes','Informes.Contenidos','PLazos']);
   //     $query = $this->find('all');
  
//        $data = $query -> toArray();  // Si pasamos el return como array no funcione el Paginator

        return $query;
    }

    public function dameProyectos(){

        $query = $this->find('list',[

            'keyField' => 'id', 
            'valueField' => 'nombre_app'
        ]);

        $data = $query -> toArray(); 

          return $data;         
    }

    public function grupoTieneDesarrollo($valor_estado, $valor_id_grupo){

        $resultado = false;

        $lista = $this->find()->toArray();

        if($valor_estado == 3){

            foreach ($lista as $p) {

                if($p->id_grupo == $valor_id_grupo && $p->id_estado == 3 ){

                    $resultado = true;
                }
            }
        }
        return $resultado;
    }
}

src/Controller/ProyectosController.php
<?php
namespace App\Controller;

use App\Controller\AppController;
 use Cake\ORM\TableRegistry;

/**
 * Proyectos Controller
 *
 * @property \App\Model\Table\ProyectosTable $Proyectos
 *
 * @method \App\Model\Entity\Proyecto[]|\Cake\Datasource\ResultSetInterface paginate($object = null, array $settings = [])
 */
class ProyectosController extends AppController
{

    /**
     * Index method
     *
     * @return \Cake\Http\Response|void
     */

    


    public function listar()
    {
        $this->paginate = [
        'sortWhitelist' => [
            'id','id_grupo','id_estado','id_cliente','nombre_app','descripcion','fecha_add','fecha_mod','Grupos.alias','Clientes.nombre', 'Estados.valor'
            ]
        ];

        $proyectos = $this->Proyectos->dameProyectosConTodo();
        $this->set('proyectos', $this->paginate($proyectos));
        $proyectos -> toArray();  
        $this->set(compact('proyectos'));
    }

    /**
     * View method
     *
     * @param string|null $id Proyecto id.
     * @return \Cake\Http\Response|void
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function ver($id = null)
    {
        $proyecto = $this->Proyectos->get($id, [
            'contain' => []
        ]);

        $this->set(compact('proyecto'));
    }

    /**
     * Add method
     *
     * @return \Cake\Http\Response|null Redirects on successful add, renders view otherwise.
     */
    public function crear()
    {
        $dataA = $this->loadModel('Grupos')->dameGrupos();
        $dataB = $this->loadModel('Estados')->dameEstados();
        $dataC = $this->loadModel('Clientes')->dameClientes();

        $proyecto = $this->Proyectos->newEntity();
        if ($this->request->is('post')) {
            $proyecto = $this->Proyectos->patchEntity($proyecto, $this->request->getData());

            if($this->Proyectos->grupoTieneDesarrollo($proyecto->id_estado, $proyecto->id_grupo)){

                $this->Flash->error(__('El grupo seleccionado ya tiene asociado un proyecto en desarrollo.'));

            }else{

                if ($this->Proyectos->save($proyecto)) {
                    $this->Flash->success(__('Los datos del nuevo proyecto han sido guardados.'));

                    return $this->redirect(['action' => 'listar']);
                }
                $this->Flash->error(__('Algo ha fallado. Inténtelo de nuevo.'));
            }
        }
        $this->set(compact('proyecto','dataA', 'dataB', 'dataC'));
    }

    /**
     * Edit method
     *
     * @param string|null $id Proyecto id.
     * @return \Cake\Http\Response|null Redirects on successful edit, renders view otherwise.
     * @throws \Cake\Network\Exception\NotFoundException When record not found.
     */
    public function editar($id = null)
    {
        $dataA = $this->loadModel('Grupos')->dameGrupos();
        $dataB = $this->loadModel('Estados')->dameEstados();
        $dataC = $this->loadModel('Clientes')->dameClientes();

        $proyecto = $this->Proyectos->get($id, [
            'contain' => []
        ]);
        if ($this->request->is(['patch', 'post', 'put'])) {
            $proyecto = $this->Proyectos->patchEntity($proyecto, $this->request->getData());

            if($this->Proyectos->grupoTieneDesarrollo($proyecto->id_estado, $proyecto->id_grupo)){

                $this->Flash->error(__('El grupo seleccionado ya tiene asociado un proyecto en desarrollo.'));

            }else{

                if ($this->Proyectos->save($proyecto)) {
                    $this->Flash->success(__('Los datos del proyecto han sido actualizados.'));

                    return $this->redirect(['action' => 'listar']);
                }
                $this->Flash->error(__('Algo ha fallado. Inténtelo de nuevo.'));
            }
        }

        $this->set(compact('proyecto', 'dataA', 'dataB', 'dataC'));
    }

    /**
     * Delete method
     *
     * @param string|null $id Proyecto id.
     * @return \Cake\Http\Response|null Redirects to index.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function eliminar($id = null)
    {
        $this->request->allowMethod(['post', 'eliminar']);
        $proyecto = $this->Proyectos->get($id);
        if ($this->Proyectos->delete($proyecto)) {
            $this->Flash->success(__('El proyecto ha sido eliminado del registro.'));
        } else {
            $this->Flash->error(__('Algo ha fallado. Inténtelo de nuevo.'));
        }

        return $this->redirect(['action' => 'listar']);
    }
}

src/Template/Proyectos/crear.ctp
<?php
/**
 * @var \App\View\AppView $this
 * @var \App\Model\Entity\Proyecto $proyecto
 */
?>
<div class="content-box-large">
    <p>
        <button class="btn btn-primary"><?= $this->Html->link(__('Ver todos'), ['action' => 'listar']) ?> </button>
    </p>  
    <div class="panel-heading">
        <div class="panel-title">Nuevo Proyecto</div>
        <div class="panel-body">
            <fieldset>
                <div class="form-group">
                    <?php 
                        echo $this->Form->create($proyecto); 
                        echo '<div class="form-group col-md-10">';
                        echo $this->Form->control('id_grupo', ['type' => 'select','label' => 'Grupo', 'options' => $dataA, 'class' => 'form-control']);
                        echo '</div>';
                        echo '<div class="form-group col-md-10">';
                        echo $this->Form->control('id_estado', ['type' => 'select','label' => 'Estado', 'options' => $dataB, 'class' => 'form-control']);
                        echo '</div>';
                        echo '<div class="form-group col-md-10">';
                        echo $this->Form->control('id_cliente', ['type' => 'select','label' => 'Cliente', 'options' => $dataC, 'class' => 'form-control']);
                        echo '</div>';
                        echo '<div class="form-group col-md-10">';
                        echo $this->Form->control('nombre_app', ['type' => 'text', 'label' => 'Nombre de la aplicación', 'class' => 'form-control']);
                        echo '</div>';
                        echo '<div class="form-group col-md-10">';
                        echo $this->Form->control('descripcion', ['type' => 'textarea', 'label' => 'Descripción', 'class' => 'form-control', 'rows' => '5', 'cols' => '5']);
                        echo '</div>';
                            //        echo $this->Form->control('fecha_add', ['empty' => true]);
                            //        echo $this->Form->control('fecha_mod', ['empty' => true]);
                        echo '<div class="form-group col-md-10">'; 
                        echo $this->Form->submit('Enviar',['class' => 'btn btn-primary form-group']);
                        echo '</div>'; 
                        echo $this->Form->end(); 
                    ?>
                </div>
            </fieldset>
        </div>    
    </div>
</div>   

src/Template/Proyectos/editar.ctp
<?php
/**
 * @var \App\View\AppView $this
 * @var \App\Model\Entity\Proyecto $proyecto
 */
?>
<!--
<nav class="large-3 medium-4 columns" id="actions-sidebar">
    <ul class="side-nav">
        <li class="heading"><?= __('Acciones') ?></li>
        <li><?= $this->Form->postLink(
                __('Eliminar'),
                ['action' => 'eliminar', $proyecto->id],
                ['confirm' => __('Está seguro de eliminar el proyecto con identificador # {0}?', $proyecto->id)]
            )
        ?></li>
        <li><?= $this->Html->link(__('Ver todos'), ['action' => 'Listar']) ?></li>
    </ul>
</nav> -->
<div class="content-box-large">
    <p>
        <button class="btn btn-primary">
            <?= $this->Html->link(__('Ver'), ['action' => 'ver', $proyecto->id]) ?>
        </button>
        <button class="btn btn-primary"><?= $this->Form->postLink(__('Eliminar'), ['action' => 'eliminar', $proyecto->id], ['confirm' => __('Está seguro de eliminar el proyecto con identificador # {0}?', $proyecto->id)]) ?></button>
        <button class="btn btn-primary"><?= $this->Html->link(__('Todos'), ['action' => 'listar']) ?> </button>
        <button class="btn btn-primary"><?= $this->Html->link(__('Crear'), ['action' => 'crear']) ?></button>
    </p> 
    <div class="panel-heading">
        <div class="panel-title">Editar Proyecto</div>
        <div class="panel-body">
            <fieldset> 
                <div class="form-group">
                    <?php 
                        echo $this->Form->create($proyecto);     
                        echo '<div class="form-group col-md-10">';
                        echo $this->Form->control('id_grupo', ['type' => 'select','label' => 'Grupo', 'options' => $dataA, 'class' => 'form-control']);
                        echo '</div>';
                        echo '<div class="form-group col-md-10">';
                        echo $this->Form->control('id_estado', ['type' => 'select','label' => 'Estado', 'options' => $dataB, 'class' => 'form-control']);
                        echo '</div>';
                        echo '<div class="form-group col-md-10">';
                        echo $this->Form->control('id_cliente', ['type' => 'select','label' => 'Cliente', 'options' => $dataC, 'class' => 'form-control']);
                        echo '</div>';
                        echo '<div class="form-group col-md-10">';
                        echo $this->Form->control('nombre_app', ['type' => 'text', 'label' => 'Nombre de la aplicación', 'class' => 'form-control']);
                        echo '</div>';
                        echo '<div class="form-group col-md-10">';
                        echo $this->Form->control('descripcion', ['type' => 'textarea', 'label' => 'Descripción', 'class' => 'form-control', 'rows' => '5', 'cols' => '5']);
                                        
                        echo '</div>';
                                //        echo $this->Form->control('fecha_add', ['empty' => true]);
                                //        echo $this->Form->control('fecha_mod', ['empty' => true]);
                        echo '<div class="form-group col-md-10">'; 
                        echo $this->Form->submit('Enviar',['class' => 'btn btn-primary form-group']);
                        echo '</div>'; 
                        echo $this->Form->end(); 
                    ?>
                </div>
            </fieldset>    
        </div>
    </div>
</div>    

src/Template/Proyectos/listar.ctp
<?php
/**
 * @var \App\View\AppView $this
 * @var \App\Model\Entity\Proyecto[]|\Cake\Collection\CollectionInterface $proyectos
 */
?>
<!--
<nav class="large-3 medium-4 columns" id="actions-sidebar">
    <ul class="side-nav">
        <li class="heading"><?= __('Acciones') ?></li>
        <li><?= $this->Html->link(__('Crear nuevo'), ['action' => 'crear']) ?></li>
        <li><?= $this->Html->link(__('TÉCNICOS'), ['controller'=> 'Tecnicos', 'action' => 'listar']) ?></li>  
    </ul>
</nav>  -->
<div class="container-fluid">
    <div class="panel-heading">
        <div class="panel-title">Proyectos registrados</div>
        <button class="btn btn-primary"><?= $this->Html->link(__('Crear'), ['action' => 'crear']) ?> </button>
    </div>
    <div class="panel-body table-responsive">
        <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="example">
            <thead>
                <tr>
                    <th scope="col">
                        <?= $this->Paginator->sort('id', ['label' => 'ID']) ?>
                    </th>
                    <th scope="col">
                        <?= $this->Paginator->sort('Grupos.alias', 'Alias grupos') ?>
                    </th>   
                    <th scope="col">
                        <?= $this->Paginator->sort('Estado.valor', 'Estado') ?>
                    </th>
                    <th scope="col">
                        <?= $this->Paginator->sort('Clientes.nombre', 'Nombre Cliente') ?>
                    </th>
                    <th scope="col">
                        <?= $this->Paginator->sort('nombre_app', ['label' => 'Nombre aplicación']) ?>
                    </th>       
                    <th scope="col" class="actions">
                        <?= __('Acciones') ?>
                    </th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($proyectos as $proyecto): ?>
                    <tr>
                        <td><?= $this->Number->format($proyecto->id) ?></td>
                        <td><?= h($proyecto->grupo->alias) ?></td>   
                        <td><?= h($proyecto->estado->valor) ?></td>
                        <td><?= h($proyecto->cliente->nombre . ' ' . $proyecto->cliente->apellidos) ?></td>
                        <td><?= h($proyecto->nombre_app) ?></td>
                        <td class="actions">
                            <button class="btn btn-primary btn-xs">
                                <?= $this->Html->link(__('Ver'), ['action' => 'ver', $proyecto->id]) ?>
                            </button>
                            <button class="btn btn-primary btn-xs">
                                <?= $this->Html->link(__('Editar'), ['action' => 'editar', $proyecto->id]) ?>
                            </button>
                            <button class="btn btn-primary btn-xs">
                                <?= $this->Form->postLink(__('Eliminar'), ['action' => 'eliminar', $proyecto->id], ['confirm' => __('Está seguro de eliminar el proyecto con identificador # {0}?', $proyecto->id)]) ?>
                            </button>
                            <button class="btn btn-primary btn-xs">
                                <?= $this->Html->link(__('Crear'), ['action' => 'crear']) ?>
                            </button>   
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
 <!--   <div class="paginator">
            <ul class="pagination">
                <?= $this->Paginator->first('<< ' . __('first')) ?>
                <?= $this->Paginator->prev('< ' . __('previous')) ?>
                <?= $this->Paginator->numbers() ?>
                <?= $this->Paginator->next(__('next') . ' >') ?>
                <?= $this->Paginator->last(__('last') . ' >>') ?>
            </ul>
            <p><?= $this->Paginator->counter(['format' => __('Page {{page}} of {{pages}}, showing {{current}} record(s) out of {{count}} total')]) ?></p>
        </div>  -->
    </div>            
</div>

src/Template/Proyectos/ver.ctp
<?php
/**
 * @var \App\View\AppView $this
 * @var \App\Model\Entity\Proyecto $proyecto
 */
?>
<!--
<nav class="large-3 medium-4 columns" id="actions-sidebar">
    <ul class="side-nav">
        <li class="heading"><?= __('Acciones') ?></li>
        <li><?= $this->Html->link(__('Editar'), ['action' => 'editar', $proyecto->id]) ?> </li>
        <li><?= $this->Form->postLink(__('Eliminar'), ['action' => 'eliminar', $proyecto->id], ['confirm' => __('Está seguro de eliminar el proyecto con identificador # {0}?', $proyecto->id)]) ?> </li>
        <li><?= $this->Html->link(__('Ver todos'), ['action' => 'listar']) ?> </li>
        <li><?= $this->Html->link(__('Crear nuevo'), ['action' => 'crear']) ?> </li>
    </ul>
</nav>   -->
<nav>
    <button class="btn btn-primary"><?= $this->Html->link('Editar', ['action' => 'editar', $proyecto->id]) ?></button>
    <button class="btn btn-primary"><?= $this->Form->postLink(__('Eliminar'), ['action' => 'eliminar', $proyecto->id], ['confirm' => __('Está seguro de eliminar el proyecto con identificador # {0}?', $proyecto->id)]) ?></button>
    <button class="btn btn-primary"><?= $this->Html->link(__('Todos'), ['action' => 'listar']) ?> </button>
    <button class="btn btn-primary"><?= $this->Html->link(__('Crear'), ['action' => 'crear']) ?></button>
</nav>  
<div>
    <h4>Datos registrados</h4>
    <table id="user" class="table table-bordered table-striped" style="clear: both">
        <tbody> 
            <tr>         
                <th width="35%" scope="row"><?= __('ID') ?></th>
                <td width="65%"><?= $this->Number->format($proyecto->id) ?></td>
            <tr>
                <th scope="row"><?= __('ID Grupo') ?></th>
                <td width="65%"><?= $this->Number->format($proyecto->id_grupo) ?></td>
            </tr>
            <tr>
                <th width="35%" scope="row"><?= __('ID Estado') ?></th>
                <td width="65%"><?= $this->Number->format($proyecto->id_estado) ?></td>
            </tr>
            <tr>
                <th width="35%" scope="row"><?= __('Id Cliente') ?></th>
                <td width="65%"><?= $this->Number->format($proyecto->id_cliente) ?></td>
            </tr>
            <tr>
                <th width="35%" scope="row"><?= __('Nombre Aplicación') ?></th>
                <td width="65%"><?= h($proyecto->nombre_app) ?></td>
            </tr>
            <tr>
                <th width="35%" scope="row"><?= __('Descripción') ?></th>
                <td width="65%"><?= h($proyecto->descripcion) ?></td>
            </tr>
            <tr>
                <th width="35%" scope="row"><?= __('Creado') ?></th>
                <td width="65%"><?= h($proyecto->fecha_add) ?></td>
            </tr>
            <tr>
                <th width="35%" scope="row"><?= __('Modificado') ?></th>
                <td width="65%"><?= h($proyecto->fecha_mod) ?></td>
            </tr>                                                   
        </tbody>
    </table>                                
</div>